services:
  notificationbot:
    build: .
    container_name: notificationbot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:16
    container_name: notificationbot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data: