services:
  notificationbot:
    build: .
    container_name: notificationbot
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: notificationbot-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: