services:
  tts:
    container_name: notificationbot-api
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9001:3001"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis-service
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: