services:
  notificationbot-api:
    build: .
    container_name: notificationbot-api
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: