services:
  tts:
    container_name: notificationbot-api
    build: .
    restart: unless-stopped
    ports:
      - "9001:3001"
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  db:
    image: postgres:16
    container_name: notificationbot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data: